Cleanup and fullname
seekingalpha/Rocket.Chat pull request #16
Opened 2022-11-22 10:43 UTC by reist

Adding Amir to reviewers for his bash mastery

2022-11-22 12:54 UTC, amiryalsa commented
Why do we need Jenkins to support giving the full file name? Why can’t we give just the version like it currently expects?

2022-11-22 13:20 UTC, reist commented
> Why do we need Jenkins to support giving the full file name? Why can’t we give just the version like it currently expects?

Because the files (and versions) are in S3, and @nmagedman stated it's easier to copy the full file name from there than to mark just the version.

2022-11-27 12:15 UTC, nmagedman requested changes

2022-11-27 12:15 UTC, nmagedman commented on Jenkinsfile.sh
> +  versionized_file="$version"
Rename this variable to `RC_TARBALL_ARG`

* Line 14 defines a convention: Template variables should end in `_ARG`.
* Implied by that is that the variables are in ALL_CAPS
* "versionized file" tells me how it was _generated_, but not what _it is_.  It's a **tarball**.

2022-11-27 12:15 UTC, nmagedman commented on Jenkinsfile.sh
>  ## Note: $version is a Jenkins job parameter
Move this comment either to line 20 (where `$version` is used) or to the top of the file (describing its inputs)

2022-11-27 12:22 UTC, nmagedman commented
> Why do we need Jenkins to support giving the full file name? Why can’t we give just the version like it currently expects?

@amiryalsa , I specifically requested this change in the description of [AR-2692](https://seekingalpha.atlassian.net/browse/AR-2692).

> Support a $version string of the full tarball name: rocket.chat-VERSION.tgz.  I find that I am usually copy the VERSION string from the full fillename anyway, so it is easier to double-click and highlight the full name.

That is, _in practice_, when I launch the Jenkins job for this, I always do the following:
* $ aws s3 ls s3://seekingalpha-rocketchat-builds/
* Find the tarball I want to deploy
* Copy/paste the version string.

To make my life easier, I want to double-click the filename (highlighting the whole thing) rather than having to carefully highlight just the part of the filename that I want.

2022-11-27 15:14 UTC, nmagedman approved these changes

2022-12-13 12:24 UTC, merged